package lt.viko.eif.emargevicius.saityno.pd3;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Spring Boot test file generated by SpringBoot
 */
@SpringBootTest
class SaitynoPd3ApplicationTests {

	@Test
	void contextLoads() {
	}

}
